check(-1 % 16 == 15, "modulo takes the sign of the divisor")
check(7 % -3 == -2, "modulo with a negative divisor")
check("x" .. 3 == "x3", "integers concatenate without a decimal point")
check("x" .. 1.5 == "x1.5", "floats concatenate")
check("" .. 0.1 + 0.2 == "0.3", "floats print with 14 significant digits")
check("10" + 1 == 11, "numeric strings in arithmetic")
check(math.abs(-3) == 3, "math.abs")
check(math.max(1, 5, 3) == 5 and math.min(4, 2, 8) == 2, "math.max and math.min")
check(math.sqrt(16) == 4, "math.sqrt")
check(math.floor(-0.5) == -1, "math.floor")
check(2 ^ 10 == 1024, "power")
check(-(3) == -3, "unary minus")
